//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
//Let us list the factors of the first seven triangle numbers:
//
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//
//What is the value of the first triangle number to have over five hundred divisors?

#include <iostream>
using namespace std;
#include <cmath>

int f(int);

int main(int argc, char argv[]){
	int n = 1;
	int number = 1;
	while( f(number) < 500 ){
		cout << number << endl;
		n++;
		number += n;
	}

	cout << number << endl;
	//76576500-----------------------------------------------------¡Ì
	system("pause");
	return 0;
}

int f(int number){
	int n;
	int div=0;
	for(n=sqrt(number); n>0; n--){
		if( !(number%n) )
			if( number/n == n ) div++;
			else div+=2;
	}
	cout << div << "\t";
	return div;
}